### ISSUE TITLE
Installation tests fail

### ISSUE THREAD

**Issue by mwaldron104** [caerusassociates/mordecai#26]
I have installed mordecai via the docker-compose command on a Ubuntu 14.04 server, but the basic unit tests fail.

$ cd resources
$ py.test
========================================= test session starts =========================================
platform linux2 -- Python 2.7.6 -- pytest-2.5.1
collected 0 items / 1 errors 

=============================================== ERRORS ================================================
_______________________________ ERROR collecting tests/test_mordecai.py _______________________________
tests/test_mordecai.py:2: in <module>
>   from ..country import CountryAPI
country.py:14: in <module>
>   import utilities
utilities.py:6: in <module>
>   from mitie import *
E   ImportError: No module named mitie
======================================= 1 error in 0.12 seconds =======================================

Any ideas?
MikeW

**Comment by johnb30** [comment]
If you ran `docker-compose up` then everything was installed into a container. This means that running the tests outside of the container would fail since the dependencies, in this case MITIE and the MITIE wrapper, are not installed.

**Comment by mwaldron104** [comment]
Thanks for your reply. I'm entirely new to docker and containers. So if I have this container running now, how does a user actually use the application? Is it totally via curl commands like the examples in the README? How would I run the tests inside the container?

Thanks,
Mike

**Comment by mwaldron104** [comment]
I learned how to mount the mordecai-master directory inside the container and ran py.test. It had 1 failure and 2 passes.
============================================================================================= test session starts =============================================================================================
platform linux2 -- Python 2.7.6 -- py-1.4.30 -- pytest-2.6.3
collected 3 items 

tests/test_mordecai.py F..

================================================================================================== FAILURES ===================================================================================================
_____________________________________________________________________________________________ test_places_api_one _____________________________________________________________________________________________

    def test_places_api_one():
        if os.environ.get('CI'):
            ci = 'circle'
            assert ci == 'circle'
        else:
            a = PlacesAPI()
            locs = {u'entities': [{u'context': ['meeting', 'happened', 'in', '.'],
                                u'score': 1.3923831181343844, u'tag': u'LOCATION',
                                u'text': 'Ontario'}]}
    
            result = a.process(locs, 'CAN')
            gold = [{u'countrycode': u'CAN', u'lat': 43.65004, u'lon': -79.90554,
                    u'placename': u'SunnyView Dental', u'searchterm': 'Ontario'}]
>           assert result == gold
E           assert [] == [{'countrycode': 'CAN', 'lat...': 'SunnyView Dental', ...}]
E             Right contains more items, first extra item: {'countrycode': 'CAN', 'lat': 43.65004, 'lon': -79.90554, 'placename': 'SunnyView Dental', ...}

tests/test_mordecai.py:19: AssertionError
-------------------------------------------------------------------------------------------- Captured stdout call ---------------------------------------------------------------------------------------------
'NoneType' object has no attribute 'filter'
==================================================================================== 1 failed, 2 passed in 223.74 seconds =====================================================================================

**Comment by johnb30** [comment]
If you ran `docker-compose up -d` in the `mordecai` directory there should be a container running in the background. Once you do that you should be able to hit `localhost:5000/places`. The README has examples on how to do that using `curl` and Python. You don't really need to worry about the tests passing within the container. They're mainly there for our CI testing. 

If hitting `localhost:5000` doesn't work then we can see what that issue is.

**Comment by chilland** [comment]
Just as a guess, is the elasticsearch container running? If the test is failing on the places endpoint and you aren't getting good results from you're request, thats the first thing you should check.

**Comment by mwaldron104** [comment]
Yes, both containers are running. 
CONTAINER ID        IMAGE                          COMMAND                CREATED             STATUS              PORTS                    NAMES
af3fdc88fe65        mordecaimaster_mordecai        "python /src/app.py"   22 hours ago        Up 5 minutes        0.0.0.0:5000->5000/tcp   mordecaimaster_mordecai_1   
2f2825b8c0aa        caerusassociates/es-geonames   "/bin/sh -c 'cd elas   23 hours ago        Up 5 minutes        9200/tcp, 9300/tcp       mordecaimaster_elastic_1    

The curl commands to localhost:5000/places seem to work ok, so I won't worry about the tests. Thanks for your help.
